### ISSUE TITLE
Two problems while building

### ISSUE THREAD

**Issue by winderica** [UniqueStudio/UniqueHackDayDashboard#50]
1. Please add `yarn.lock` to `.gitignore`, or it will throw an error while installing packages in node v10.4.0. It works well after deleting `yarn.lock`.
![image](https://user-images.githubusercontent.com/13536040/41295249-abbf431c-6e8c-11e8-83c1-8c5c7f34b72d.png)
2. It keeps building a certain file for an extremely long time, which appears both on my Windows 10 (  v1803 x64 ) and Ubuntu 18.04 ( WSL ). Looking forward to more people's test results.
![image](https://user-images.githubusercontent.com/13536040/41297513-db77ec44-6e91-11e8-9cfc-3c8f58b02a8d.png)

**Comment by farawaaay** [comment]
Great.
I just tried to build on my Debian server and **everything is OK**.
```sh
$ node -v
v10.4.0
$ yarn -v
1.5.1
$ npm -v
6.1.0
```
I cloned the full repository and run:
```sh
$ yarn --ignore-engines
```

and 

```sh
$ yarn start

```
or
```sh
$ yarn build

```

Everything is OK.


I think problem lies on your missing of `--ignore-engines`.

Then I `rm yarn.lock` and `rm -rf ./node_modules` , re-install with `yarn --ignore-engines`, no problems reported while I `yarn build`.

**Comment by winderica** [comment]
🤣Thanks for your reply.
I will try it tomorrow.

**Comment by winderica** [comment]
I clone the repository again, but there are still some problems using `yarn --ignore-engines`.

1. ![image](https://user-images.githubusercontent.com/13536040/41326773-3c05c746-6ef3-11e8-83ea-30e3d30d1a26.png)
I have `python3` installed already, and it seems that it requires `python2`. So I installed `python2` but it failed again.
![image](https://user-images.githubusercontent.com/13536040/41326994-3ebdd8c4-6ef4-11e8-970a-9ebf49662f74.png)

2. And if I ignore the error of 1. and run `yarn start` or `yarn build` directly, it will show another error.
![image](https://user-images.githubusercontent.com/13536040/41326780-47cc5f5e-6ef3-11e8-8179-99521c7c21cc.png)

**Comment by farawaaay** [comment]
Try to reinstall make?

**Comment by farawaaay** [comment]
This project needs the post-install script to transpile antd-pro code for better build experience.


The problem shown in your last pic will disappear if your installation is OK.

**Comment by winderica** [comment]
Reinstall make did make sense, it works finally.
